// @generated by protoc-gen-es v2.2.3
// @generated from file api/gclock_service.proto (package gclock.api, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file api/gclock_service.proto.
 */
export const file_api_gclock_service = /*@__PURE__*/
  fileDesc("ChhhcGkvZ2Nsb2NrX3NlcnZpY2UucHJvdG8SCmdjbG9jay5hcGkiIgoOR2V0VGltZVJlcXVlc3QSEAoIdGltZXpvbmUYASABKAkiUQoPR2V0VGltZVJlc3BvbnNlEhQKDGN1cnJlbnRfdGltZRgBIAEoCRIUCgxjdXJyZW50X3pvbmUYAiABKAkSEgoKdXRjX29mZnNldBgDIAEoCTJTCg1HQ2xvY2tTZXJ2aWNlEkIKB0dldFRpbWUSGi5nY2xvY2suYXBpLkdldFRpbWVSZXF1ZXN0GhsuZ2Nsb2NrLmFwaS5HZXRUaW1lUmVzcG9uc2VCiwEKDmNvbS5nY2xvY2suYXBpQhJHY2xvY2tTZXJ2aWNlUHJvdG9QAVocZ2l0aHViLmNvbS9iaGJkZXYvZ2Nsb2NrL2FwaaICA0dBWKoCCkdjbG9jay5BcGnKAgpHY2xvY2tcQXBp4gIWR2Nsb2NrXEFwaVxHUEJNZXRhZGF0YeoCC0djbG9jazo6QXBpYgZwcm90bzM");

/**
 * Describes the message gclock.api.GetTimeRequest.
 * Use `create(GetTimeRequestSchema)` to create a new message.
 */
export const GetTimeRequestSchema = /*@__PURE__*/
  messageDesc(file_api_gclock_service, 0);

/**
 * Describes the message gclock.api.GetTimeResponse.
 * Use `create(GetTimeResponseSchema)` to create a new message.
 */
export const GetTimeResponseSchema = /*@__PURE__*/
  messageDesc(file_api_gclock_service, 1);

/**
 * @generated from service gclock.api.GClockService
 */
export const GClockService = /*@__PURE__*/
  serviceDesc(file_api_gclock_service, 0);

