// @generated by protoc-gen-es v2.2.3
// @generated from file api/gclock_service.proto (package gclock.api, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/gclock_service.proto.
 */
export declare const file_api_gclock_service: GenFile;

/**
 * @generated from message gclock.api.GetTimeRequest
 */
export declare type GetTimeRequest = Message<"gclock.api.GetTimeRequest"> & {
  /**
   * @generated from field: string timezone = 1;
   */
  timezone: string;
};

/**
 * Describes the message gclock.api.GetTimeRequest.
 * Use `create(GetTimeRequestSchema)` to create a new message.
 */
export declare const GetTimeRequestSchema: GenMessage<GetTimeRequest>;

/**
 * @generated from message gclock.api.GetTimeResponse
 */
export declare type GetTimeResponse = Message<"gclock.api.GetTimeResponse"> & {
  /**
   * @generated from field: string current_time = 1;
   */
  currentTime: string;

  /**
   * @generated from field: string current_zone = 2;
   */
  currentZone: string;

  /**
   * @generated from field: string utc_offset = 3;
   */
  utcOffset: string;
};

/**
 * Describes the message gclock.api.GetTimeResponse.
 * Use `create(GetTimeResponseSchema)` to create a new message.
 */
export declare const GetTimeResponseSchema: GenMessage<GetTimeResponse>;

/**
 * @generated from service gclock.api.GClockService
 */
export declare const GClockService: GenService<{
  /**
   * @generated from rpc gclock.api.GClockService.GetTime
   */
  getTime: {
    methodKind: "unary";
    input: typeof GetTimeRequestSchema;
    output: typeof GetTimeResponseSchema;
  },
}>;

